/**
 * Protocol-neutral token usage counters mirroring the intermediate representation (IR) shape.
 *
 * All token counts are finite, non-negative safe integers.
 * An absent (undefined) field indicates that the provider or protocol did not report that counter,
 * which is semantically distinct from reporting a count of zero.
 */
export interface Usage {
  /**
   * The number of input (prompt) tokens consumed by the request.
   */
  readonly input: number;

  /**
   * The number of output (completion) tokens generated by the provider.
   */
  readonly output: number;

  /**
   * Total token count (sum of input and output tokens, plus any provider-specific additions).
   * When omitted, consumers calculate total as `input + output`.
   */
  readonly total?: number;

  /**
   * Number of prompt tokens read directly from prompt cache / context cache.
   */
  readonly cacheReadInput?: number;

  /**
   * Number of prompt tokens written into prompt cache / context cache for subsequent requests.
   */
  readonly cacheWriteInput?: number;

  /**
   * Number of internal reasoning/thinking tokens generated during response processing.
   */
  readonly reasoningOutput?: number;
}
