/**
 * @fileoverview Protocol-neutral token usage counters for requests and responses.
 *
 * Normalizes provider token metrics (prompt, completion, cache hits/writes, reasoning)
 * into a single unified {@link Usage} shape consumed by pricing estimators, stream
 * accumulators, and terminal trace records.
 */

/**
 * Protocol-neutral token usage counters for an admitted request.
 *
 * All numeric counters are non-negative safe integers. Optional fields indicate
 * that the upstream provider or protocol does not report that metric (distinct from 0).
 */
export interface Usage {
  /** Total prompt/input tokens processed by the provider before cache adjustments. */
  readonly input: number;

  /** Total completion/output tokens generated by the provider (excluding reasoning tokens). */
  readonly output: number;

  /**
   * Provider-reported total token count. If omitted, consumers fall back to
   * calculating input + output tokens.
   */
  readonly total?: number;

  /** Input prompt tokens served directly from the provider's prompt cache. */
  readonly cacheReadInput?: number;

  /** Input tokens written into the provider's prompt cache during request processing. */
  readonly cacheWriteInput?: number;

  /** Internal model reasoning / thought tokens produced during generation. */
  readonly reasoningOutput?: number;
}
